// frontend/src/routes/login/+page.svelte
<script lang="ts">
    import { goto } from '$app/navigation';
    import Corbado from '@corbado/web-js';
    import {onMount} from 'svelte';
 
    let authElement: HTMLDivElement;
 
    onMount(async () => {
        await Corbado.load({
            projectId: "pro-9274187161272909532",
            darkMode: "off",

        });
        if (Corbado.user) {
            goto('/');
        }
        Corbado.mountAuthUI(
            authElement, {
                onLoggedIn: () => {
                    goto('/app');
                },
            })
    })
</script>
 
<div bind:this={authElement}></div>

// frontend/src/app/login/login.component.ts
import { Component, ElementRef, OnInit, ViewChild } from "@angular/core";
import { Router } from "@angular/router";
import Corbado from "@corbado/web-js/";

@Component({
  selector: "app-login",
  imports: [],
  templateUrl: "./login.component.html",
  styleUrl: "./login.component.scss",
})
export class LoginComponent implements OnInit {
  @ViewChild("corbadoAuth", { static: true }) authElement!: ElementRef;

  constructor(private router: Router) {}

  async ngOnInit() {
    // Load and initialize Corbado SDK when the component mounts
    await Corbado.load({
      projectId: "pro-9274187161272909532",
      darkMode: "off",
    });
    // mount Corbado auth UI for the user to sign in or sign up
    Corbado.mountAuthUI(this.authElement.nativeElement, {
      onLoggedIn: () => {
        this.router.navigateByUrl("/profile");
      },
    });
  }
}

<div #corbadoAuth id="corbado-auth"></div>
